In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df= pd.read_csv(r'Bodyfat.csv')
df

,Density,bodyfat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
0,1.0708,12.3,23,154.25,67.75,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1
1,1.0853,6.1,22,173.25,72.25,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2
2,1.0414,25.3,22,154.00,66.25,34.0,95.8,87.9,99.2,59.6,38.9,24.0,28.8,25.2,16.6
3,1.0751,10.4,26,184.75,72.25,37.4,101.8,86.4,101.2,60.1,37.3,22.8,32.4,29.4,18.2
4,1.0340,28.7,24,184.25,71.25,34.4,97.3,100.0,101.9,63.2,42.2,24.0,32.2,27.7,17.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,1.0736,11.0,70,134.25,67.00,34.9,89.2,83.6,88.8,49.6,34.8,21.5,25.6,25.7,18.5
248,1.0236,33.6,72,201.00,69.75,40.9,108.5,105.0,104.5,59.6,40.8,23.2,35.2,28.6,20.1
249,1.0328,29.3,72,186.75,66.00,38.9,111.1,111.5,101.7,60.3,37.3,21.5,31.3,27.2,18.0
250,1.0399,26.0,72,190.75,70.50,38.9,108.3,101.3,97.8,56.0,41.6,22.7,30.5,29.4,19.8
251,1.0271,31.9,74,207.50,70.00,40.8,112.4,108.5,107.1,59.3,42.2,24.6,33.7,30.0,20.9

In [ ]:
df.isnull().sum()

Density    0
bodyfat    0
Age        0
Weight     0
Height     0
Neck       0
Chest      0
Abdomen    0
Hip        0
Thigh      0
Knee       0
Ankle      0
Biceps     0
Forearm    0
Wrist      0
dtype: int64

In [ ]:
#replace the missing values
mean = df['bodyfat'].mean()
df['bodyfat'].fillna(mean, inplace=True)

median1 = df['Age'].median()
df['Age'].fillna(median1, inplace=True)

mean2 = df['Weight'].mean()
df['Weight'].fillna(mean2, inplace=True)

mean3 = df['Height'].mean()
df['Height'].fillna(mean3, inplace=True)

mean4 = df['Neck'].mean()
df['Neck'].fillna(mean4, inplace=True)

mean5 = df['Chest'].mean()
df['Chest'].fillna(mean5, inplace=True)

mean6 = df['Abdomen'].mean()
df['Abdomen'].fillna(mean6, inplace=True)

mean7 = df['Hip'].mean()
df['Hip'].fillna(mean7, inplace=True)

In [ ]:
df.isnull().sum()

Density    0
bodyfat    0
Age        0
Weight     0
Height     0
Neck       0
Chest      0
Abdomen    0
Hip        0
Thigh      0
Knee       0
Ankle      0
Biceps     0
Forearm    0
Wrist      0
dtype: int64

In [ ]:
All missing values are filled.